광고 목록 반환 api
tsulocalize/chzzkGamble pull request #11
Opened 2024-11-28 06:28 UTC by unifolio0

디스코드 봇 기능을 위한 광고 목록 반환 api 추가했습니다

2024-11-28 07:29 UTC, tsulocalize requested changes

2024-11-28 07:29 UTC, tsulocalize commented on src/main/java/com/chzzkGamble/advertise/service/AdvertiseService.java
> +    }
1. 앞으로 승인해야 할 광고 목록만 보여주는 기능이어야 할 것 같네요. 승인 거절한 광고가 조회되지 않도록 할 방법을 고안해주세요.
2. 메서드 사이 엔터 부탁드립니다.

2024-11-28 07:29 UTC, tsulocalize commented on src/main/java/com/chzzkGamble/exception/AdvertiseExceptionCode.java
> +    INVALID_AD_PERIOD(HttpStatus.BAD_REQUEST, 2_001, "광고 기한은 1 ~ 30내에서만 가능합니다."),
`일`이라는 표현을 추가해보시죠!

2024-11-28 07:29 UTC, tsulocalize commented on src/main/java/com/chzzkGamble/advertise/dto/ApprovalAdvertiseResponse.java
> +        );
승인된 광고 목록은 사용자에게 보일 부분이라 일부 수정이 필요할 것 같네요.
아래 항목만 포함되도록 해주세요.
- id
- name
- imageUrl
- 확률(probability)

2024-12-03 08:45 UTC, unifolio0 commented on src/main/java/com/chzzkGamble/exception/AdvertiseExceptionCode.java
> +    INVALID_AD_PERIOD(HttpStatus.BAD_REQUEST, 2_001, "광고 기한은 1 ~ 30내에서만 가능합니다."),
수정했습니다!

2024-12-03 11:57 UTC, unifolio0 commented on src/main/java/com/chzzkGamble/advertise/dto/ApprovalAdvertiseResponse.java
> +        );
수정했습니다!

2024-12-03 12:23 UTC, unifolio0 commented on src/main/java/com/chzzkGamble/advertise/service/AdvertiseService.java
> +    }
날짜가 null인 목록만 가져오도록 수정했습니다!

2024-12-04 07:52 UTC, merged