광고 정책 수정에 따른 코드 수정
tsulocalize/chzzkGamble pull request #15
Opened 2024-12-16 07:43 UTC by unifolio0

`totalAmount`를 `double`로 선언했는데 괜찮을까요?

2024-12-18 04:38 UTC, tsulocalize requested changes
변경된 요구사항이 많네요 ㅎㅎ
확인 부탁드려요!

2024-12-18 04:38 UTC, tsulocalize commented on src/main/java/com/chzzkGamble/advertise/domain/Advertise.java
> +    }
제가 광고 금액이 1000원 단위라고 말한 적 있었나요?

2024-12-18 04:38 UTC, tsulocalize commented on src/main/java/com/chzzkGamble/advertise/domain/AdvertiseMap.java
> +    private static final Advertise DEFAULT_ADVERTISE = new Advertise("Default Advertise", "IMAGE_URL_HERE", 1000L, 10);
기본 광고 - '광고 한번 해보세요' 하는 광고
1. 기본 광고를 10일이 아닌 평생 적용할 수 있는 방법을 고안해주세요
2. 기본 광고가 다른 광고와 함께 일정한 비율로 등장할 수 있게 해주세요
(ex. 전체 광고의 10%는 기본 광고가 등장한다)

2024-12-19 05:37 UTC, unifolio0 commented on src/main/java/com/chzzkGamble/advertise/domain/Advertise.java
> +    }
해당 검증 삭제했습니다!

2024-12-19 06:20 UTC, unifolio0 commented on src/main/java/com/chzzkGamble/advertise/domain/AdvertiseMap.java
> +    private static final Advertise DEFAULT_ADVERTISE = new Advertise("Default Advertise", "IMAGE_URL_HERE", 1000L, 10);
반영했습니다!

2024-12-19 07:39 UTC, merged