api key 검증 기능
tsulocalize/chzzkGamble pull request #5
Opened 2024-11-09 02:54 UTC by unifolio0

- Filter를 사용한 api key 검증
- aws의 파라미터 스토어에서 값을 가져오는 기능 (로컬에서는 테스트 해봤지만 ec2에서 테스트는 아직 못 해봄)
- 서브 모듈 추가

2024-11-09 03:57 UTC, tsulocalize requested changes
> 파라미터 스토어에서 값을 받아와 로컬에 저장할 방법을 찾다보니 현재와 같은 구조로 구현했는데 다른 좋은 방안이 있는지

- 괜찮은 방법이라고 생각합니다. 나중에 편의성을 위해 값 업데이트 할 떄 개발자에게도 알려줄 수 있으면 좋겠네요

> ApiKeyHolder에 ThreadLocal과 같은 걸 적용할 필요가 있는지

- 굳이? 싶네요... 쓰레드 별로 다른 API KEY를 갖는 것도 아니니까
 - 디스코드 광고 신청 중에 시간 차이 때문에 오류가 생기면 오류 메시지만 잘 보여주면 될 것 같아요

2024-11-09 03:57 UTC, tsulocalize commented on src/main/java/com/chzzkGamble/auth/config/ApiKeyFilterConfig.java
> +        registrationBean.addUrlPatterns("/advertise/*", "/auth/*");
advertise 패키지에서 `광고 생성` 이랑 `광고 승인` 만 인가할 것 같습니다.
`*`를 쓰지 않는 게 어떨까요?

2024-11-09 03:57 UTC, tsulocalize commented on src/main/java/com/chzzkGamble/auth/config/ApiKeyHolder.java
> +@Configuration
`@Component`는 어떤가요

2024-11-09 03:57 UTC, tsulocalize commented on src/main/java/com/chzzkGamble/auth/cnotroller/AuthController.java
> +    @GetMapping("/auth/update/key")
GET 과 /update/key 엔드포인트가 서로 잘 어울리는 것 같지 않다고 느껴지네요...!

저는 내부 값을 바꾸는 요청은 GET을 사용하지 않긴 하는데 의견 남겨주세요~

2024-11-09 03:57 UTC, tsulocalize commented on src/main/java/com/chzzkGamble/auth/AuthService.java
> +        GetParameterRequest getParameterRequest = GetParameterRequest.builder().name(keyName).withDecryption(true).build();
`.`이 많을 때 엔터를 쳐주면 가독성이 올라갈 것 같네요 (특히 빌더 패턴)

2024-11-09 04:56 UTC, unifolio0 commented on src/main/java/com/chzzkGamble/auth/config/ApiKeyFilterConfig.java
> +        registrationBean.addUrlPatterns("/advertise/*", "/auth/*");
수정했습니다!

2024-11-09 04:57 UTC, unifolio0 commented on src/main/java/com/chzzkGamble/auth/config/ApiKeyHolder.java
> +@Configuration
왜 `@Configuration`을 사용했는지 모르겠네요... 졸면서 했나...
확인 결과 빈으로 등록할 필요가 없는 것 같아 해당 어노테이션은 삭제했습니다

2024-11-09 04:57 UTC, unifolio0 commented on src/main/java/com/chzzkGamble/auth/cnotroller/AuthController.java
> +    @GetMapping("/auth/update/key")
PUT으로 수정했습니다!

2024-11-09 04:57 UTC, unifolio0 commented on src/main/java/com/chzzkGamble/auth/AuthService.java
> +        GetParameterRequest getParameterRequest = GetParameterRequest.builder().name(keyName).withDecryption(true).build();
수정했습니다!

2024-11-11 04:49 UTC, tsulocalize approved these changes

2024-11-11 04:49 UTC, merged

2024-11-12 00:16 UTC, xogns1514 commented on src/main/java/com/chzzkGamble/auth/config/ApiKeyHolder.java
> +@Configuration
왜 졸면서 하시는거에요 :비또졸: