Fix: 치지직에서 ping을 보내지 않을 시 연결 끊기는 오류 해결
tsulocalize/chzzkGamble pull request #6
Opened 2024-11-11 23:53 UTC by xogns1514

### 문제상황
- 치지직 서버에서 ping을 보내지 않으면 연결이 끊기는 현상이 간헐적으로 나타납니다.

### 해결방안
- 치지직 서버에 먼저 ping을 보내 소켓 연결을 유지합니다. 

### 변경사항
![image](https://github.com/user-attachments/assets/2115196f-f57c-478d-8bd1-d2c1937891b0)
- 연결된 소켓에 30초 주기로 ping을 보내 연결을 유지합니다. 
- 소켓 연결 책임 클래스 분리
- 메시지 전송 유틸 클래스 분리

2024-11-14 09:03 UTC, tsulocalize requested changes
리뷰가 늦었네요;;
여러 의견을 내봤는데, 다른 의견이 있으면 가감없이 말씀부탁드립니다~

2024-11-14 09:03 UTC, tsulocalize commented on src/main/java/com/chzzkGamble/chzzk/chat/service/ChzzkWebSocketClient.java
> +            MessageSender.sendTextMessage(session, new PingMessage());
PingMessage(PongMessage) 객체가 매번 생성되지 않게 만들수도 있을 것 같네요!

2024-11-14 09:03 UTC, tsulocalize commented on src/main/java/com/chzzkGamble/chzzk/chat/service/ChzzkWebSocketClient.java
>              throw new ChzzkException(ChzzkExceptionCode.CHAT_CONNECTION_ERROR, e.getMessage());
👍 하나 배워갑니다잉

2024-11-14 09:03 UTC, tsulocalize commented on src/main/java/com/chzzkGamble/chzzk/chat/service/ChzzkChatService.java
>          }
1. 이미 Chat이 열려있는데 reconnect하는 이유가 있나요? 이러면 같은 connection이 2개 생길 것 같다는 생각이 듭니다.
2. 기존 code에는 없었지만 `lastEventPublished`를 업데이트 해주는 게 좋을 것 같네요
3. 우선 서버 1대로 런칭 계획이라 synchronized로 동시성 문제를 해결해도 괜찮을 것 같아요

2024-11-14 09:03 UTC, tsulocalize commented on src/main/java/com/chzzkGamble/chzzk/chat/service/ChzzkChatService.java
>      }
저는 메서드명을 `createChat`이나 `createNewChat`정도로 할 것 같은데 의견을 들려주세요!

2024-11-14 09:03 UTC, tsulocalize commented on src/main/java/com/chzzkGamble/chzzk/chat/service/ChzzkWebSocketClient.java
> +    private static final int TIMEOUT = 30;
초 단위라는 인식이 될 수 있으면 좋겠네요. 주석? 상수명? 어떤 방식이든

2024-11-19 06:46 UTC, xogns1514 reviewed
안녕하세요 우주~~리뷰 반영 및 답변 달아두었어요.
`connectChatRoom` 메서드에서 논의할게 좀 있는 거 같네요..ㅎㅎ
확인하고 답변 달아주시면 감사하겠습니다~

2024-11-19 06:46 UTC, xogns1514 commented on src/main/java/com/chzzkGamble/chzzk/chat/service/ChzzkChatService.java
>      }
`createNewChat` 좋네욤~

2024-11-19 06:46 UTC, xogns1514 commented on src/main/java/com/chzzkGamble/chzzk/chat/service/ChzzkWebSocketClient.java
> +    private static final int TIMEOUT = 30;
좋네요~`TIMEOUT_SECONDS`로 상수명을 변경했습니다.

2024-11-19 06:46 UTC, xogns1514 commented on src/main/java/com/chzzkGamble/chzzk/chat/service/ChzzkChatService.java
>          }
1. `isChatAlreadyOpen`로직을 보면 DB에서 해당 Chat의 open상태를 통해서 검사를 하고 있습니다. DB에서의 상태만을 검사해서, 웹소켓이 연결되어 있다는 사실을 확신할 수 없다고 생각했습니다. 우주 말대로 reconnect하게 되면 웹소켓 세션을 새로 생성하게 되겠네요. 해당 문제는 reconnect 시도시, 이미 웹소켓 세션이 존재한다면 재사용하고, 존재하지 않으면 새로 생성하는 식으로 해결할 수 있을 것 같네요~ 우주의 생각은 어떤가요?
2. `lastEventPublished`를 `isChatAlreadyOpen` 분기문 내에서도 업데이트 해주는 것을 말하는 걸까요? `initiateNewChatConnection` 메서드 내에서는 `lastEventPublished`를 이미 업데이트 하고 있습니다!
3. 메서드에 `synchronized` 키워드를 붙이는 방법을 말씀하시는걸까요? 그렇게 될 경우 저번에 얘기 나누었던 것 처럼, 해당 메서드는 `@Transaction` 으로 동작하기 때문에 트랜잭션 경계와 메서드 경계의 불일치로 동시성 제어가 제대로 이루어지지 않을 것 같습니다! 제가 생각한 해결방법은 DB 레벨에서 lock(비관적 또는 낙관적)을 통해 제어 해야할 것 같아요. 
우주는 어떻게 생각하시나요??

2024-11-19 06:46 UTC, xogns1514 commented on src/main/java/com/chzzkGamble/chzzk/chat/service/ChzzkWebSocketClient.java
> +            MessageSender.sendTextMessage(session, new PingMessage());
static 변수로 선언해두었습니다.

2024-11-19 08:45 UTC, tsulocalize commented on src/main/java/com/chzzkGamble/chzzk/chat/service/ChzzkChatService.java
>          }
1. DB에서 Chat의 Open 상태만으로 웹소켓 연결을 확신할 수 없다면, `chatClients`에서 client.isConnected() 를 추가로 검증하면 되지 않을까요? reconnect라는 메서드 이름은 [다시 연결한다]라는 의미를 가지고 있고 이는 [기존 연결은 끊겼다]라는 배경을 내포하고 있다는 느낌을 받았습니다.(개인적 의견)

2. 
> lastEventPublished를 isChatAlreadyOpen 분기문 내에서도 업데이트 해주는 것을 말하는 걸까요?

네, 맞습니다. 기존 chat에 대한 연결 또한 새로운 이벤트로 보아야 서비스 이용 시 예상하지 못한 동작을 방지할 수 있다고 생각합니다!
자세히 설명하자면 아래와 같은 예시가 있을 수 있을 것 같습니다.

가정 : [chat 연결 유지 시간 = 마지막 이벤트로 부터 10분]
1. 한 시청자가 방송인 A에 대한 chat을 연결했고, 이로부터 9분이 지났다.
2. 방송인 A가 chat 연결을 요청했고, 기존 연결이 있으므로 새로운 연결을 하지는 않는다.
3. 1분 뒤 컨텐츠를 진행하려했던 방송인 A의 chat 연결은 마지막 이벤트(1)로부터 10분이 지났기 때문에 연결이 끊겨버렸다.

3. 
> @Transaction 으로 동작하기 때문에 트랜잭션 경계와 메서드 경계의 불일치로 동시성 제어가 제대로 이루어지지 않을 것

이 부분은 잘 이해가 되지 않네요. 자세한 얘기를 들어보려 했지만, 잠실에 안계셔서 ㅠㅠ

> DB 레벨에서 lock(비관적 또는 낙관적)을 통해 제어

위 메서드 현재 로직을 간단히 표현하면 다음과 같습니다.
[존재 여부 검증 - 웹소켓 연결 - chat DB에 저장]
lock을 통해 검증하자고 하면 table 전체에 lock을 걸어야 하고, 웹소켓이 연결 될 때까지 lock을 풀 수 없습니다. 웹소켓 연결이 보통 4-5초 정도는 걸리는데 그 동안 table 전체 lock을 거는 부분에 대한 성능 저하가 크게 우려됩니다.
물론 `synchronized` 키워드를 사용한다고 해서 위 성능 저하가 해결되는 것은 아닙니다만...

2024-11-20 07:57 UTC, tsulocalize requested changes
테스트 코드에서 궁금한 점이 있어 추가 리뷰 남겼습니다!
(아마 마지막 리뷰일 것 같네요!)

2024-11-20 07:57 UTC, tsulocalize commented on src/test/java/com/chzzkGamble/chzzk/chat/service/ChzzkChatFacadeTest.java
> +        ExecutorService executorService = Executors.newFixedThreadPool(10);
numberOfThreads = 5 인데, 왜 여긴 10인가요?

2024-11-20 07:57 UTC, tsulocalize commented on src/test/java/com/chzzkGamble/chzzk/chat/service/ChzzkChatFacadeTest.java
> +        Mockito.doAnswer(invocation -> {
static import를 쓰면 더 좋겠네요!
(Assertions 포함)

2024-11-20 07:57 UTC, tsulocalize commented on src/test/java/com/chzzkGamble/chzzk/chat/service/ChzzkChatFacadeTest.java
> +        CountDownLatch startLatch = new CountDownLatch(1);
startLatch의 역할은 무엇인가요?

2024-11-20 07:57 UTC, tsulocalize commented on src/test/java/com/chzzkGamble/chzzk/chat/service/ChzzkChatFacadeTest.java
> +        Map<String, Boolean> connectionStates = new ConcurrentHashMap<>();
connectionStates가 테스트 검증에 사용되지 않는 것 같은데,
`.doNothing()`이나 `.thenReturn(null)`과 차이는 무엇인가요?

2024-11-20 08:36 UTC, xogns1514 commented on src/test/java/com/chzzkGamble/chzzk/chat/service/ChzzkChatFacadeTest.java
> +        ExecutorService executorService = Executors.newFixedThreadPool(10);
5로 일치시켜도 되겠네요~👍🏻

2024-11-20 08:36 UTC, xogns1514 commented on src/test/java/com/chzzkGamble/chzzk/chat/service/ChzzkChatFacadeTest.java
> +        CountDownLatch startLatch = new CountDownLatch(1);
각 쓰레드들이 같은 타이밍에 실행되도록 하는 것입니다. count를 1로 설정해둔뒤에, 메인 쓰레드에서 countDown하는 순간 쓰레들이 동작합니다.

2024-11-20 08:36 UTC, xogns1514 commented on src/test/java/com/chzzkGamble/chzzk/chat/service/ChzzkChatFacadeTest.java
> +        Map<String, Boolean> connectionStates = new ConcurrentHashMap<>();
`connectionStates` 를 사용하게 된 이유는 doAnswer부분에서 처음에 요청을 시도한 쓰레드에게는 false, 이후 쓰레드에게는 true를 반환하도록 모킹하기 위해서 입니다.

사용하게 된 계기는 다음과 같아요.
만약 연결하지 못하는 channelName을 작성하게되면, `connect` 시 에러가 발생해서 커넥션이 생성되지 않아요. 
하지만 `connectionManager.isConnected(channelName)` 에서 false를 반환해서, 분기문 처리가 되지 않고, 새로운 채팅을 만드려고 합니다. 즉, 커넥션은 생성되지 않고 데이터베이스에는 같은 channelName을 가진 Chat이 쌓이게 됩니다. 

결론적으로 실제 소켓 연결하는 부분을 모킹하고, 현재 연결가능한 channelName에 동시 요청이 발생한 상황을 가정하기 위해 사용했습니다. 

- doAnswer는 doNothing과 다르게 호출된 인자를 이용해서 내부적으로 동작을 제어할 수 있습니다~!

더 좋은 해결방법이 있다면 제안해주세요

2024-11-20 21:50 UTC, tsulocalize commented on src/test/java/com/chzzkGamble/chzzk/chat/service/ChzzkChatFacadeTest.java
> +        Map<String, Boolean> connectionStates = new ConcurrentHashMap<>();
확인했습니다! 꼼꼼히 확인하셨네요~

2024-11-20 21:51 UTC, tsulocalize approved these changes
연결하는 channelName이 온전하다(실제로 존재한다)는 전제하에 코드가 진행되고 있었네요.
현재는 channelName을 chzzk api를 통해 가져오고 사용하고 있기 때문에 문제가 발생하지 않고 있었고, 추후 문제 해결 방안에 대해 고민해볼 여지는 있겠습니다!

수고하셨습니다!!

2024-11-20 21:51 UTC, merged