룰렛 서비스 리팩토링
tsulocalize/chzzkGamble pull request #7
Opened 2024-11-13 16:59 UTC by jimi567

1. 요청하신 RouletteService 리팩토링 해봤습니다.
2. 기존 코드 vote 부분에 트랜잭션이 적용이 안될 것 같아서, 도네이션 이벤트 리스너를 별도의 빈으로 빼서 구현했어요.
3. DonationEvent에 대한 Stub를 구현해뒀어요. 지금 당장은 안쓰이긴해요.

2024-11-14 09:36 UTC, tsulocalize requested changes
의견 몇가지 남겼습니다!
꼭 제 의견에 따라갈 필요는 없고, 생각이 다른 부분 있으면 댓글 남겨주세요~

2024-11-14 09:36 UTC, tsulocalize commented on src/main/java/com/chzzkGamble/gamble/roulette/service/RouletteService.java
> +        log.info("isActive Transaction = {}", TransactionSynchronizationManager.isActualTransactionActive());
위 로그는 test용인가요? 실제로 필요해서 작성된 건가요?

2024-11-14 09:36 UTC, tsulocalize commented on src/main/java/com/chzzkGamble/gamble/GambleService.java
> +public interface GambleService {
인터페이스 서비스를 만든 이유는 무엇인가요? 
제 추측으로는 여러 서비스가 위 인터페이스를 구현하기 위한 것 같아보이는데,
앞으로 추가될 서비스가 위 인터페이스를 구현한다고 했을 때,
1. 다른 GambleService가 `vote`를 한다는 보장이 없다.
2. Bean 등록된 서비스 중 특정 하나의 서비스만 생성자 주입받을 수 있다. (여러 서비스를 주입받게 할 수도 있지만, 그렇게 되면 인터페이스의 존재 이유가 없어진다)
와 같은 문제가 당장은 생각나는 것 같습니다.

2024-11-14 09:36 UTC, tsulocalize commented on src/main/java/com/chzzkGamble/gamble/roulette/service/RouletteService.java
> +    private static final Logger log = LoggerFactory.getLogger(RouletteService.class);
기존 코드와 일치하게 @Slf4j 를 사용하는 걸 추천드립니다!

2024-11-14 09:36 UTC, tsulocalize commented on src/main/java/com/chzzkGamble/gamble/roulette/domain/RouletteElement.java
> +        return new RouletteElement(name, 0, roulette);
메서드 명이 명확하지 않은 것처럼 느껴지네요.
처음 봤을 때 `First`가 있으니 `Second`도 있는 건가? 라는 생각이 들었습니다.
자주 사용되는 `.of()` 나 `.newInstance()`도 괜찮고 새로운 객체를 만든다는 내용이 담기면 좋겠네요

2024-11-14 09:36 UTC, tsulocalize commented on src/test/java/com/chzzkGamble/gamble/DonationHandlerTest.java
> +    @Disabled
@Disabled 테스트에 대해서는 다른 개발자들이 이해하기 쉽도록 테스트 내용과 disable한 이유에 대해서 설명이 추가되면 좋을 것 같습니다.

2024-11-14 09:36 UTC, tsulocalize commented on src/test/java/com/chzzkGamble/support/StubDonationEvent.java
> +public class StubDonationEvent extends DonationEvent {
stub goood~

2024-11-14 14:36 UTC, jimi567 commented on src/main/java/com/chzzkGamble/gamble/roulette/domain/RouletteElement.java
> +        return new RouletteElement(name, 0, roulette);
룰렛에 기존에 없던 새로운 요소를 추가한다는 개념을 담고싶었는데,  newInstance 좋을 것 같아요. 보편적으로 사용되고 제가 담고자했던 의미도 담기네요

2024-11-16 19:33 UTC, jimi567 commented
일단 얘기나누면서,
변경되는 부분이랑 추가 기능 까지 구현헀습니다.

2024-11-17 12:15 UTC, jimi567 commented on src/main/java/com/chzzkGamble/gamble/roulette/service/RouletteService.java
> +        log.info("isActive Transaction = {}", TransactionSynchronizationManager.isActualTransactionActive());
확인 끝난걸로 알아서 삭제했습니다.

2024-11-17 12:15 UTC, jimi567 commented on src/main/java/com/chzzkGamble/gamble/GambleService.java
> +public interface GambleService {
얘기 나누면서 정해진 부분 반영해봤는데 어색한 부분 한 번 더 피드백 부탁드립니당

2024-11-17 15:42 UTC, tsulocalize requested changes

2024-11-17 15:42 UTC, tsulocalize commented on src/main/java/com/chzzkGamble/gamble/roulette/dto/RouletteCheeseUnitUpdateRequest.java
> +) {
rouletteUnit, CheeseUnit, RouletteCheeseUnit
세가지 용어가 혼재되어 있는 것 같습니다, 하나로 통일하는 게 좋을 것 같네요
개인적으로는 rouletteUnit이 어떨까 싶네요

2024-11-17 15:42 UTC, tsulocalize commented on src/main/java/com/chzzkGamble/gamble/roulette/service/RouletteService.java
> +        return rouletteRepository.save(new Roulette(channelName, rouletteUnit));
rouletteUnit을 항상 보내도록 할 예정입니다. (default 1000으로)
룰렛을 `new Roulette(channelName, rouletteUnit)`으로만 생성하도록 하고,
Request에서 notBlank로 하시죠!

2024-11-18 22:00 UTC, jimi567 commented on src/main/java/com/chzzkGamble/gamble/roulette/dto/RouletteCheeseUnitUpdateRequest.java
> +) {
rouletteUnit 통일하겟슴당!

2024-11-18 22:16 UTC, jimi567 commented on src/main/java/com/chzzkGamble/gamble/roulette/service/RouletteService.java
> +        return rouletteRepository.save(new Roulette(channelName, rouletteUnit));
확인했습니다.

request에서 타입을 기본타입(int)로 바꾸고 positive 어노테이션으로 검증하도록 변경했습니다.

2024-11-19 03:03 UTC, tsulocalize approved these changes
수고 많으셨습니당~

2024-11-19 03:03 UTC, merged