봇의 기능에 따라 광고 도메인 수정
tsulocalize/chzzkGamble pull request #9
Opened 2024-11-22 07:49 UTC by unifolio0

1. 광고 테이블에 활성화 여부, 시작 날짜, 종료 날짜 추가 했습니다.
2. 광고 승인 api 추가 했습니다.

2024-11-22 14:22 UTC, tsulocalize requested changes
우선 눈에 보이는 것 먼저 리뷰 남겼습니다!

2024-11-22 14:22 UTC, tsulocalize commented on src/main/java/com/chzzkGamble/advertise/dto/AdvertiseCreateResponse.java
> +}
id는 헤더에 담아주는 것 같은데, 추가로 response를 추는 이유가 있을까요?

2024-11-22 14:22 UTC, tsulocalize commented on src/main/java/com/chzzkGamble/advertise/domain/Advertise.java
> +    private LocalDateTime endDate;
createdAt도 필요할 것 같습니다!

2024-11-22 14:22 UTC, tsulocalize commented on src/main/java/com/chzzkGamble/advertise/domain/Advertise.java
> +    }
1. 생성자는 반드시 필요한 경우가 아니면 체이닝을 해주세요!
2. 요구사항을 다시 명확히 해야할 것 같습니다.

- 광고 기간 미지정 시 (10일 간 노출)
- 광고 기간 지정 시 (n일 간 노출) (n = 1~30)
- 시작일 == 승인 시점
- 종료일 == 시작일 + 광고 기간
- 광고 기간 컬럼 추가(not null)

2024-11-22 14:22 UTC, tsulocalize commented on src/main/java/com/chzzkGamble/advertise/domain/Advertise.java
> +        this.active = false;
default 값이 false인데 false로 만든다는 것은 true -> false로 바꿀 일이 있다고 가정한 것일까요?

2024-11-22 14:22 UTC, tsulocalize commented on src/main/java/com/chzzkGamble/advertise/service/AdvertiseService.java
> +    }
동시성을 위해 낙관적 락을 걸어야할 것 같네요

2024-11-23 03:45 UTC, unifolio0 commented on src/main/java/com/chzzkGamble/advertise/dto/AdvertiseCreateResponse.java
> +}
헤더에는 `advertise/{id}`와 같은 형태로 전송이 되고 있기도 하고 파이썬에서 추출할때는 헤더보단 바디에 있는 게 더 편해서 바디에 담아줬습니다

2024-11-23 03:45 UTC, unifolio0 commented on src/main/java/com/chzzkGamble/advertise/domain/Advertise.java
> +    private LocalDateTime endDate;
혹시 이유를 더 자세히 알려주실 수 있을까요? 저는 startDate과 endDate만으로 충분하다고 생각해서 지운 거라서요

2024-11-23 03:46 UTC, unifolio0 commented on src/main/java/com/chzzkGamble/advertise/domain/Advertise.java
> +        this.active = false;
넵, 이미 게시되어 있는 광고를 어떤 사유로 인해 광고 기간이 지나기 전에 내릴 상황이 생길 수 있다고 판단했습니다.

2024-11-23 03:48 UTC, unifolio0 commented on src/main/java/com/chzzkGamble/advertise/service/AdvertiseService.java
> +    }
혹시 어떤 이유로 동시성이 발생할 지 알려주실 수 있나요? 지금 로직은 true로 세팅하는 로직이라 race condition이 발생하지 않는다고 생각합니다.

2024-11-23 03:50 UTC, unifolio0 commented on src/main/java/com/chzzkGamble/advertise/domain/Advertise.java
> +    }
광고 기간은 왜 컬럼으로 필요한 지 알 수 있나요? 지금 startDate와 endDate으로 충분히 활용 가능할 것 같은데 광고 기간 컬럼을 추가하는 건 불필요하다고 판단해서요.

나머지 리뷰는 반영하겠습니다!

2024-11-23 04:05 UTC, unifolio0 commented on src/main/java/com/chzzkGamble/advertise/domain/Advertise.java
> +    private LocalDateTime endDate;
만약 모든 엔티티에 createdAt을 넣을 거라면 추상클래스로 BaseEntity를 만들어 여기에 createdAt을 넣고 모든 엔티티가 해당 클래스를 상속받도록 만드는 건 어떤가요?

2024-11-23 04:27 UTC, tsulocalize commented on src/main/java/com/chzzkGamble/advertise/dto/AdvertiseCreateResponse.java
> +}
추가적인 정보가 담길 수도 있으니 dto를 반환해도 나쁘지 않겠네요!

2024-11-23 04:29 UTC, tsulocalize commented on src/main/java/com/chzzkGamble/advertise/domain/Advertise.java
> +    private LocalDateTime endDate;
저는 언제나 코드가 잘못 동작할 수 있다고 생각하고 이를 방지하기 위해 정보를 최대한 기록해두는 게 좋은 것 같더라구요!

BaseEntity 만드는 것도 좋네요!
LastModifedAt도 추가할 수 있을 것 같기도...

2024-11-23 04:36 UTC, tsulocalize commented on src/main/java/com/chzzkGamble/advertise/service/AdvertiseService.java
> +    }
도메인에 reject 메서드가 있다는 건 언젠가 비즈니스 로직에서 활용될 것이라 추측했습니다!

흠... 물론 광고 승인에서 충돌이 발생할 일은 거의 없고 있더라도 금방 수정할 수 있긴하죠.
불필요하다고 생각되시면 이 리뷰는 넘기셔도 좋습니다!

2024-11-23 04:39 UTC, tsulocalize commented on src/main/java/com/chzzkGamble/advertise/domain/Advertise.java
> +    }
제 생각은 이렇습니다
1. 광고 생성 시점에서 시작일과 종료일은 미정이다
2. 승인되는 순간부터 광고 기한만큼 노출한다
3. 그렇다면 유저가 설정한 광고 기한을 어딘가 저장은 해야될텐데...

2024-11-25 07:41 UTC, unifolio0 commented on src/main/java/com/chzzkGamble/advertise/domain/Advertise.java
> +    private LocalDateTime endDate;
BaseEntity를 만들었습니다! 다만 다른 엔티티는 제가 추가해도 되는진 몰라서 광고에만 extends했습니다

2024-11-25 07:41 UTC, unifolio0 commented on src/main/java/com/chzzkGamble/advertise/domain/Advertise.java
> +    }
전부 적용했습니다

2024-11-25 07:43 UTC, unifolio0 commented on src/main/java/com/chzzkGamble/advertise/service/AdvertiseService.java
> +    }
해당 api는 디스코드를 통해서 호출 되기에 동시성 문제가 발생하진 않는다고 생각합니다. 락은 간단히 어노테이션으로 적용할 수 있으니 나중에 적용해도 문제 없을 것 같아 우선 적용하진 않았습니다.

2024-11-25 08:20 UTC, tsulocalize requested changes
아마? 마지막 리뷰일 것 같습니다!

2024-11-25 08:20 UTC, tsulocalize commented on src/main/java/com/chzzkGamble/advertise/domain/Advertise.java
> +    private Integer adPeriod;
`일` 기반이라는 표현이 나타나면 더 좋을 것 같네요

2024-11-25 08:20 UTC, tsulocalize commented on src/main/java/com/chzzkGamble/advertise/domain/Advertise.java
> +    }
- Clock Bean에 의해 LocalDateTime.now()가 동작하게 해주세요!
- endDate가 adPeriod에 따라 변해야하지 않을까요?

2024-11-25 08:20 UTC, tsulocalize commented on src/main/java/com/chzzkGamble/advertise/domain/Advertise.java
> +    }
이 생성자는 왜 필요한 걸까요?

2024-11-25 08:58 UTC, unifolio0 commented on src/main/java/com/chzzkGamble/advertise/domain/Advertise.java
> +    }
수정했습니다

2024-11-25 09:00 UTC, unifolio0 commented on src/main/java/com/chzzkGamble/advertise/domain/Advertise.java
> +    private Integer adPeriod;
수정했습니다

2024-11-25 09:09 UTC, unifolio0 commented on src/main/java/com/chzzkGamble/advertise/domain/Advertise.java
> +    }
수정했습니다

2024-11-25 09:24 UTC, merged